server:
  port: 8011

spring:
  datasource:
    username: root
    password: zhj123
    url: jdbc:mysql://localhost:3306/test01_bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
#    配置静态资源访问的路径 (index.html的文件是默认直接作为首页访问的)  [classpath:/static/HTML/ ]
    static-locations: [classpath:/HTML/ ]

#    配置静态资源访问的路径前缀,对动态资源没有用，动态资源只看@RequestMapping("/***")里面的路径
  mvc:
    static-path-pattern: /res/**


mybatis:
  mapper-locations: classpath:/Mapper/*.xml







